In [1]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv('../Dataset/appartments.csv').drop(22)

In [3]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."

In [4]:
df['PropertySubName'][0]

'2, 3, 4 BHK Apartment in Sector 113, Gurgaon'

In [5]:
df['NearbyLocations'][0]

"['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar', 'Park Hospital', 'Gurgaon Railway Station']"

In [6]:
df['LocationAdvantages'][0]

"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"

In [7]:
df['PriceDetails'][0]

"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}"

In [8]:
df['TopFacilities'][0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

## recommender 1. Based on topfacilities

In [9]:
def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [10]:
df['FacilitiesStr'] = df['TopFacilities'].apply(' '.join)

In [11]:
df['FacilitiesStr'][0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

In [12]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [13]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [14]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.18809342, 0.18809342,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16873099, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27811185, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17445059, 0.17445059,
       0.15589841, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16355699, 0.29372893, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18084455, 0.18084455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17445059, 0.        , 0.24773259, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06440364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2659983 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12932284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21010446, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16522746,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25610081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15177345,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21412748, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14918792,
       0.29372893, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16355699, 0.16355699, 0.        ,
       0.        , 0.        , 0.06493586, 0.06493586, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [15]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [16]:
cosine_sim1.shape

(246, 246)

In [23]:
cosine_sim1[0]

array([1.        , 0.01095159, 0.        , 0.01084196, 0.03680554,
       0.09606236, 0.01298851, 0.11694113, 0.08581866, 0.18383703,
       0.0867874 , 0.38885046, 0.05456836, 0.01060269, 0.2795812 ,
       0.09962026, 0.04464395, 0.        , 0.07993835, 0.01409962,
       0.0285075 , 0.12384884, 0.05425096, 0.01123476, 0.10737203,
       0.03793557, 0.01535356, 0.01028889, 0.02808416, 0.10018755,
       0.01137482, 0.21113653, 0.0142793 , 0.01129043, 0.10627372,
       0.03785414, 0.0937186 , 0.0525833 , 0.1835331 , 0.03549845,
       0.05483513, 0.02642675, 0.        , 0.01058227, 0.03182732,
       0.1457341 , 0.03045638, 0.00985505, 0.05257774, 0.11627835,
       0.01963182, 0.03610692, 0.04770997, 0.        , 0.12505784,
       0.11581035, 0.19094326, 0.09816112, 0.03080674, 0.04080013,
       0.02763568, 0.0847239 , 0.09457611, 0.32781666, 0.24934736,
       0.08049929, 0.01141942, 0.03395175, 0.15377243, 0.09399471,
       0.02681204, 0.01067862, 0.17078732, 0.05827849, 0.03868907,
       0.14260628, 0.02976066, 0.03708214, 0.01138199, 0.02733452,
       0.03363298, 0.03664496, 0.02718676, 0.01173882, 0.01208323,
       0.01123168, 0.234192  , 0.08855074, 0.05205294, 0.01137387,
       0.02727198, 0.02472072, 0.16031398, 0.02498028, 0.02769076,
       0.00973803, 0.11781452, 0.03083008, 0.02521512, 0.07449088,
       0.        , 0.13856029, 0.01115607, 0.03116647, 0.13160509,
       0.03087745, 0.02744126, 0.03362375, 0.0935317 , 0.08630729,
       0.05449703, 0.05893398, 0.01221845, 0.31791768, 0.11533012,
       0.30214002, 0.03018622, 0.05167431, 0.03424089, 0.03939486,
       0.04635938, 0.01088278, 0.02811557, 0.01243929, 0.02775505,
       0.0392735 , 0.02923397, 0.03720202, 0.10657132, 0.06794655,
       0.01196626, 0.02867211, 0.        , 0.03686015, 0.19542479,
       0.01259778, 0.07461274, 0.08191087, 0.15592731, 0.06240619,
       0.01519832, 0.04401699, 0.03431966, 0.08379044, 0.05438318,
       0.09293793, 0.08304386, 0.08951964, 0.11713447, 0.03489456,
       0.03102186, 0.01130416, 0.0201316 , 0.34593545, 0.03894103,
       0.08016756, 0.08357372, 0.05328449, 0.03804512, 0.01568978,
       0.29893277, 0.04913695, 0.        , 0.08380988, 0.01065466,
       0.0120037 , 0.01121578, 0.0140206 , 0.15803808, 0.01196303,
       0.03462729, 0.03839233, 0.03621217, 0.09850961, 0.03579246,
       0.01109347, 0.05782322, 0.        , 0.07700378, 0.07916551,
       0.        , 0.02558462, 0.01451285, 0.01029861, 0.08234522,
       0.29952264, 0.03852792, 0.01207339, 0.05372732, 0.02844649,
       0.        , 0.24984838, 0.0529365 , 0.        , 0.0267927 ,
       0.03813403, 0.09246143, 0.01170745, 0.10320949, 0.03964664,
       0.03939424, 0.09369352, 0.0614111 , 0.21425146, 0.07985547,
       0.03203462, 0.03553691, 0.        , 0.07567062, 0.01016108,
       0.28139162, 0.02953928, 0.09141567, 0.19043959, 0.00882122,
       0.03947752, 0.09988262, 0.00360938, 0.20424822, 0.08640965,
       0.03618169, 0.08710521, 0.08256148, 0.09395579, 0.07730358,
       0.03474074, 0.09897679, 0.12882389, 0.18780304, 0.02901375,
       0.01125469, 0.01064386, 0.01176836, 0.02997846, 0.03222598,
       0.08202999, 0.24436672, 0.03105818, 0.02710435, 0.01487903,
       0.08829355, 0.03535932, 0.19521445, 0.01183329, 0.08656385,
       0.0110727 ])

In [19]:
def recommend_properties(property_name, cosine_sim=cosine_sim1):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [20]:
recommend_properties("DLF The Arbour")

           PropertyName            SimilarityScore
64      Ace Palm Floors   (63, 0.4529382062441955)
217         Yashika 104  (216, 0.4199606322926784)
93       JMS The Nation   (92, 0.4166584649363288)
154       India Rashtra   (153, 0.398954234680194)
0    Smartworld One DXP   (0, 0.38885046199432893)

## recommender 2. based on price

In [27]:
import json
def refined_parse_modified_v2(detail_str):
    try:
        details = json.loads(detail_str.replace("'", "\""))
    except:
        return {}

    extracted = {}
    for bhk, detail in details.items():
        # Extract building type
        extracted[f'building type_{bhk}'] = detail.get('building_type')

        # Parsing area details
        area = detail.get('area', '')
        area_parts = area.split('-')
        if len(area_parts) == 1:
            try:
                value = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area low {bhk}'] = value
                extracted[f'area high {bhk}'] = value
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
        elif len(area_parts) == 2:
            try:
                extracted[f'area low {bhk}'] = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area high {bhk}'] = float(area_parts[1].replace(',', '').replace(' sq.ft.', '').strip())
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None

        # Parsing price details
        price_range = detail.get('price-range', '')
        price_parts = price_range.split('-')
        if len(price_parts) == 2:
            try:
                extracted[f'price low {bhk}'] = float(price_parts[0].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                extracted[f'price high {bhk}'] = float(price_parts[1].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                if 'L' in price_parts[0]:
                    extracted[f'price low {bhk}'] /= 100
                if 'L' in price_parts[1]:
                    extracted[f'price high {bhk}'] /= 100
            except:
                extracted[f'price low {bhk}'] = None
                extracted[f'price high {bhk}'] = None

    return extracted

In [28]:
data_refined = []

for _, row in df.iterrows():
    features = refined_parse_modified_v2(row['PriceDetails'])
    
    # Construct a new row for the transformed dataframe
    new_row = {'PropertyName': row['PropertyName']}
    
    # Populate the new row with extracted features
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        new_row[f'building type_{config}'] = features.get(f'building type_{config}')
        new_row[f'area low {config}'] = features.get(f'area low {config}')
        new_row[f'area high {config}'] = features.get(f'area high {config}')
        new_row[f'price low {config}'] = features.get(f'price low {config}')
        new_row[f'price high {config}'] = features.get(f'price high {config}')
    
    data_refined.append(new_row)

df_final_refined_v2 = pd.DataFrame(data_refined).set_index('PropertyName')

In [29]:
df_final_refined_v2

,building type_1 BHK,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,building type_2 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,...,building type_1 RK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,building type_Land,area low Land,area high Land,price low Land,price high Land
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,None,NaN,NaN,NaN,NaN,Apartment,1370.0,1370.0,2.0000,2.40,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
M3M Crown,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,,500.0,4329.0,2.05,41.13
Sobha City,None,NaN,NaN,NaN,NaN,Apartment,1381.0,1692.0,1.5500,3.21,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Signature Global City 93,None,NaN,NaN,NaN,NaN,Independent Floor,981.0,1118.0,0.9301,1.06,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,None,NaN,NaN,NaN,NaN,Apartment,964.0,964.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Pyramid Urban Homes 2,Apartment,335.0,398.0,23.45,0.2786,Apartment,500.0,625.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Satya The Hermitage,None,NaN,NaN,NaN,NaN,Apartment,1450.0,1450.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
BPTP Spacio,None,NaN,NaN,NaN,NaN,Apartment,1000.0,1079.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
SS The Coralwood,None,NaN,NaN,NaN,NaN,Apartment,1320.0,1425.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [32]:
# ohe on categorical col
categorical_columns = df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [33]:
ohe_df = pd.get_dummies(df_final_refined_v2, columns=categorical_columns, drop_first=True)

In [34]:
ohe_df.fillna(0,inplace=True)

In [35]:
ohe_df

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0.0,0.0,0.00,0.0000,1370.0,1370.0,2.0000,2.40,1850.0,2050.0,...,False,False,False,False,False,False,False,False,False,False
M3M Crown,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1605.0,2170.0,...,False,False,False,False,False,False,False,False,False,False
Adani Brahma Samsara Vilasa,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1800.0,3150.0,...,False,False,True,False,False,True,False,False,False,False
Sobha City,0.0,0.0,0.00,0.0000,1381.0,1692.0,1.5500,3.21,1711.0,2343.0,...,False,False,False,False,False,False,False,False,False,False
Signature Global City 93,0.0,0.0,0.00,0.0000,981.0,1118.0,0.9301,1.06,1235.0,1530.0,...,True,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.0,0.0,0.00,0.0000,964.0,964.0,0.0000,0.00,1127.0,1127.0,...,False,False,False,False,False,False,False,False,False,False
Pyramid Urban Homes 2,335.0,398.0,23.45,0.2786,500.0,625.0,0.0000,0.00,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
Satya The Hermitage,0.0,0.0,0.00,0.0000,1450.0,1450.0,0.0000,0.00,1991.0,1991.0,...,False,False,False,False,False,False,False,False,False,False
BPTP Spacio,0.0,0.0,0.00,0.0000,1000.0,1079.0,0.0000,0.00,1225.0,1865.0,...,False,False,False,False,False,False,False,False,False,False
SS The Coralwood,0.0,0.0,0.00,0.0000,1320.0,1425.0,0.0000,0.00,1750.0,1890.0,...,False,False,False,False,False,False,False,False,False,False

In [36]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
ohe_df_normalized = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=ohe_df.index)

In [37]:
ohe_df_normalized.head()

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-0.252266,-0.169584,-0.105197,-0.082332,1.223499,1.020101,-0.173712,1.158423,0.553787,0.370864,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
M3M Crown,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.293086,0.472749,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Adani Brahma Samsara Vilasa,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.500583,1.304803,...,-0.289310,-0.063888,2.683282,-0.063888,-0.171139,3.924283,-0.236208,-0.111111,-0.216353,-0.063888
Sobha City,-0.252266,-0.169584,-0.105197,-0.082332,1.240497,1.470610,-0.198425,1.680336,0.405879,0.619632,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Signature Global City 93,-0.252266,-0.169584,-0.105197,-0.082332,0.622383,0.667529,-0.232468,0.295011,-0.100626,-0.070634,...,3.456497,-0.063888,2.683282,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888

In [38]:
cosine_sim2 = cosine_similarity(ohe_df_normalized)

In [39]:
cosine_sim2.shape

(246, 246)

In [65]:
def recommend_properties_with_scores(property_name, cosine_sim=cosine_sim2):
    # Get the index of the property that matches the name
    idx = ohe_df_normalized.index.get_loc(property_name)

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName':ohe_df_normalized.index[property_indices].tolist(),
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [66]:
recommend_properties_with_scores('M3M Golf Hills')

              PropertyName            SimilarityScore
0  AIPL The Peaceful Homes   (80, 0.9554620840555186)
1       Smartworld One DXP    (0, 0.9546700864873817)
2           Unitech Escape  (233, 0.9530919579069698)
3              M3M Capital   (22, 0.9511561073306115)
4               BPTP Terra   (29, 0.9431284475619686)

## recommender 3. based on nearBylocation

In [58]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [69]:
import ast
location_matrix = {}
for index, row in df.iterrows():
    distances = {}
    for location, distance in ast.literal_eval(row['LocationAdvantages']).items():
        distances[location] = distance_to_meters(distance)
    location_matrix[index] = distances

# Convert the dictionary to a dataframe
location_df = pd.DataFrame.from_dict(location_matrix, orient='index')

# Display the first few rows
location_df.head()

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
0,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,NaN,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,5300.0,NaN,NaN,NaN,2500.0,8800.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,NaN,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,5500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

D:\Software\anaconda\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [77]:
def get_similar_columns(df, similarity_threshold=85):
    columns_to_drop = set()  # To store columns that will be dropped
    similar_columns = []  # To store tuples of similar columns
    
    columns = df.columns.tolist()
    
    # Iterate over each column and compare it with every other column
    for i, col in enumerate(columns):
        if col not in columns_to_drop:
            # Get all similar columns using fuzzy matching
            for other_col in columns[i+1:]:
                similarity_score = fuzz.ratio(col.lower(), other_col.lower())
                
                # If similarity score is above the threshold, mark the column for removal
                if similarity_score >= similarity_threshold:
                    columns_to_drop.add(other_col)
                    similar_columns.append((col, other_col, similarity_score))
    
    # Drop similar columns from the DataFrame
    df_cleaned = df.drop(columns=columns_to_drop)
    
    return df_cleaned, similar_columns

# Example usage with a DataFrame 'df'
df_cleaned, similar_columns = get_similar_columns(location_df, similarity_threshold=90)

In [78]:
for col1, col2, score in similar_columns:
    print(f"Columns '{col1}' and '{col2}' are similar with a similarity score of {score}.")

Columns 'Gurgaon Railway Station' and 'Gurgaon Old Railway Station' are similar with a similarity score of 92.
Columns 'Gurgaon Railway Station' and 'Gurgaon railway station' are similar with a similarity score of 100.
Columns 'Dwarka Sector 21, Metro Station' and 'Dwarka Sector 21 Metro Station' are similar with a similarity score of 98.
Columns 'Dwarka Sector 21, Metro Station' and 'Dwarka Sector 21 Metro station' are similar with a similarity score of 98.
Columns 'Dwarka Sector 21, Metro Station' and 'Dwarka sector 21 metro station' are similar with a similarity score of 98.
Columns 'Fun N Food Waterpark' and 'Fun N Food Water Park' are similar with a similarity score of 98.
Columns 'Fun N Food Waterpark' and 'Fun N Food WaterPark' are similar with a similarity score of 100.
Columns 'Dwarka Expressway' and 'Dwaraka Expressway' are similar with a similarity score of 97.
Columns 'Dwarka Expressway' and 'Dwarka expressway' are similar with a similarity score of 100.
Columns 'Tau DeviLal Sports Complex' and 'Tau Devi Lal Sports Complex' are similar with a similarity score of 98.
Columns 'Rapid Metro Station Sector 56' and 'Rapid Metro Station Sector 55 56' are similar with a similarity score of 95.
Columns 'Golf Course Ext Rd' and 'Golf Course Ext Road' are similar with a similarity score of 95.
Columns 'Golf Course Ext Rd' and 'Golf Corse Ext. Rd.' are similar with a similarity score of 92.
Columns 'Golf Course Ext Rd' and 'Golf Course Extn Road' are similar with a similarity score of 92.
Columns 'Mehrauli-Gurgaon Road' and 'Mehrauli-Gurgaon Rd' are similar with a similarity score of 95.
Columns 'TERI Golf Course' and 'Teri Golf Course' are similar with a similarity score of 100.
Columns 'Rions Hospital' and 'Rion's Hospital' are similar with a similarity score of 97.
Columns 'IGI Airport' and 'IGIA Airport' are similar with a similarity score of 96.
Columns 'Sapphire 83 Mall' and 'Sapphire Mall' are similar with a similarity score of 90.
Columns 'Sapphire 83 Mall' and 'Sapphire 93 Mall' are similar with a similarity score of 94.
Columns 'AapnoGhar' and 'Aapno Ghar' are similar with a similarity score of 95.
Columns 'NH 48' and 'NH 248' are similar with a similarity score of 91.
Columns 'IMT Manesar' and 'Imt Manesar' are similar with a similarity score of 100.
Columns 'Golf Course Extension Road' and 'Golf Course Extension Rd' are similar with a similarity score of 96.
Columns 'Golf Course Extension Road' and 'Golf course extension road' are similar with a similarity score of 100.
Columns 'Euro International School, Sector- 109' and 'Euro International School, Sector- 109.' are similar with a similarity score of 99.
Columns 'Euro International School, Sector- 109' and 'Euro International School, Sector 37D' are similar with a similarity score of 91.
Columns 'Euro International School, Sector- 109' and 'Euro International School, Sector 84' are similar with a similarity score of 92.
Columns 'Euro International School, Sector- 109' and 'Euro International School, sector- 51' are similar with a similarity score of 96.
Columns 'Indira Gandhi Intl Airport' and 'Indira Gandhi Int. Airport' are similar with a similarity score of 96.
Columns 'Pataudi Road' and 'Pataudi road' are similar with a similarity score of 100.
Columns 'Pataudi Road' and 'Pataudi Rd' are similar with a similarity score of 91.
Columns 'RPS International School' and 'Euro International School' are similar with a similarity score of 90.
Columns 'RPS International School' and 'GEMS International School' are similar with a similarity score of 90.
Columns 'RPS International School' and 'DPS International School' are similar with a similarity score of 96.
Columns 'RPS International School' and 'Gems International School' are similar with a similarity score of 90.
Columns 'RPS International School' and 'S N International School' are similar with a similarity score of 92.
Columns 'Iris Broadway Mall' and 'IRIS Broadway Mall' are similar with a similarity score of 100.
Columns 'Sector 55-56 Metro Station' and 'Sector 55/56 Metro Station' are similar with a similarity score of 96.
Columns 'Sector 55-56 Metro Station' and 'Sector 53-54 Metro Station' are similar with a similarity score of 92.
Columns 'Sector 55-56 Metro Station' and 'Sector 55 Metro Station' are similar with a similarity score of 94.
Columns 'Sector 55-56 Metro Station' and 'Sector 55-56 Metro station' are similar with a similarity score of 100.
Columns 'Sector 55-56 Metro Station' and 'Sector 53 Metro Station' are similar with a similarity score of 90.
Columns 'Sector 55-56 Metro Station' and 'Sector 55-56 Rapid Metro Station' are similar with a similarity score of 90.
Columns 'Sector 55-56 Metro Station' and 'Sector 55-56 rapid metro station' are similar with a similarity score of 90.
Columns 'Sector 55-56 Metro Station' and 'Sector 55-56 metro station' are similar with a similarity score of 100.
Columns 'Omaxe Gurgaon Mall' and 'OMAXE Gurgaon Mall' are similar with a similarity score of 100.
Columns 'Badshahpur Sohna Rd Hwy,Sector 48' and 'Badshahpur Sohna Rd Hwy, Sector 68' are similar with a similarity score of 96.
Columns 'National Highway  48' and 'National Highway 48' are similar with a similarity score of 97.
Columns 'National Highway  48' and 'National Highway-48' are similar with a similarity score of 92.
Columns 'National Highway  48' and 'National Highway 8' are similar with a similarity score of 95.
Columns 'Vatika Town Square-INXT' and 'Vatika Town Square-INXT Mall' are similar with a similarity score of 90.
Columns 'Badshahpur Sohna Hwy' and 'Badshahpur Sohna Rd Hwy' are similar with a similarity score of 93.
Columns 'Delhi - Jaipur Expressway' and 'Delhi Jaipur Expressway' are similar with a similarity score of 96.
Columns 'St. Xavier's High School' and 'St Xavier High School' are similar with a similarity score of 93.
Columns 'Miracles Apollo Cradle Spectra Hospital' and 'Miracles Apollo Cradle/Spectra Hospital' are similar with a similarity score of 97.
Columns 'Miracles Apollo Cradle Spectra Hospital' and 'Miracles Apollo Cradle /Spectra Hospital' are similar with a similarity score of 99.
Columns 'Faridabad Gurgaon Road' and 'Faridabad - Gurgaon Road' are similar with a similarity score of 96.
Columns 'Faridabad Gurgaon Road' and 'Faridabad - Gurgaon Rd' are similar with a similarity score of 91.
Columns 'Huda Metro Station' and 'Huda metro station' are similar with a similarity score of 100.
Columns 'Huda Metro Station' and 'HUDA Metro Station' are similar with a similarity score of 100.
Columns 'Huda Metro Station' and 'Huda Metro station' are similar with a similarity score of 100.
Columns 'Southern Peripheral Rd' and 'Southern Peripheral Road' are similar with a similarity score of 96.
Columns 'NH 248A' and 'NH 248 A' are similar with a similarity score of 93.
Columns 'NH 248A' and 'NH 248' are similar with a similarity score of 92.
Columns 'NH 248A' and 'NH248A' are similar with a similarity score of 92.
Columns 'Delhi Public School, Sector 84' and 'Delhi Public School Sector 84' are similar with a similarity score of 98.
Columns 'Delhi Public School, Sector 84' and 'Delhi Public School, Sector 103' are similar with a similarity score of 92.
Columns 'Aarvy Hospital' and 'Arvy Hospital' are similar with a similarity score of 96.
Columns 'Infinity Business Park' and 'infinity Business Park' are similar with a similarity score of 100.
Columns 'Sector 86 Road' and 'Sector 84 Road' are similar with a similarity score of 93.
Columns 'Medanta -The Medicity' and 'Medanta-The Medicity' are similar with a similarity score of 98.
Columns 'Medanta -The Medicity' and 'Medanta The Medicity' are similar with a similarity score of 98.
Columns 'Medanta -The Medicity' and 'Medanta - The Medicity' are similar with a similarity score of 98.
Columns 'Amma Hospital' and 'Aman Hospital' are similar with a similarity score of 92.
Columns 'GD Goenka World School' and 'G D Goenka World School' are similar with a similarity score of 98.
Columns 'KR Mangalam University' and 'K. R. Mangalam University' are similar with a similarity score of 94.
Columns 'KR Mangalam University' and 'K.R. Mangalam University' are similar with a similarity score of 96.
Columns 'G D Goenka University' and 'Gd goenka university' are similar with a similarity score of 98.
Columns 'G D Goenka University' and 'GD Goenka University' are similar with a similarity score of 98.
Columns 'Scottish High International School' and 'Scottish International School' are similar with a similarity score of 92.
Columns 'Holiday Inn Express Gurugram Sector 50' and 'Holiday Inn Express Gurugram Sec 50' are similar with a similarity score of 96.
Columns 'Park Inn' and 'Park inn' are similar with a similarity score of 100.
Columns 'IFFCO Chowk Metro Station' and 'Iffco Chowk Metro Station' are similar with a similarity score of 100.
Columns 'Euro Int School, Sector 37D, Gurugram' and 'Euro Intl School, Sector 37D, Gurugram' are similar with a similarity score of 99.
Columns 'Reliance Trends Newtown Square Mall' and 'RELIANCE TRENDS Newtown Square Mall' are similar with a similarity score of 100.
Columns 'SGT University' and 'SGT UNIVERSITY' are similar with a similarity score of 100.
Columns 'CD International School' and 'DPS International School' are similar with a similarity score of 94.
Columns 'Basai Dhankot Railway Station' and 'Basai Dhancourt Railway Station' are similar with a similarity score of 93.
Columns 'Proposed Metro Station' and 'Propose Metro Station' are similar with a similarity score of 98.
Columns 'Delhi International Airport' and 'IG International Airport' are similar with a similarity score of 90.
Columns 'KMP Corridor' and 'KMP corridor' are similar with a similarity score of 100.
Columns 'PVR Drive In Theatre' and 'PVR Drive in Theatre' are similar with a similarity score of 100.
Columns 'PVR Drive In Theatre' and 'PVR Drive In Theater' are similar with a similarity score of 95.
Columns 'Sector 53-54 Rapid Metro' and 'Sector 55-56 Rapid Metro' are similar with a similarity score of 92.
Columns 'HDFC Bank ATM' and 'HDFC bank ATM' are similar with a similarity score of 100.
Columns 'IFFCO Chowk' and 'Iffco Chowk' are similar with a similarity score of 100.
Columns 'Gaytri Public School' and 'Garima Public School' are similar with a similarity score of 90.
Columns 'International Airport' and 'IG International Airport' are similar with a similarity score of 93.
Columns 'Lemon Tree Hotel' and 'Lemon Tree Hotel,' are similar with a similarity score of 97.
Columns 'Golf Course Road' and 'Golf Course Rd' are similar with a similarity score of 93.
Columns 'Sector 42-43 Metro Station' and 'Sector 42-43 Metro station' are similar with a similarity score of 100.
Columns 'Sector 42-43 Metro Station' and 'Sector 42-43 Rapid Metro Station' are similar with a similarity score of 90.
Columns 'Artimis hospital' and 'Artemis Hospital' are similar with a similarity score of 94.
Columns 'Huda City Centre' and 'Huda city center' are similar with a similarity score of 94.
Columns 'Global city centre' and 'Global City Centre' are similar with a similarity score of 100.
Columns 'Vardaan hospital and trauma centre' and 'Vardaan Hospital & Trauma Centre' are similar with a similarity score of 94.
Columns 'Vardaan hospital and trauma centre' and 'Vardaan Hospital and Trauma Centre' are similar with a similarity score of 100.
Columns 'Sector 55-56 metro' and 'Sector 55-56 Metro' are similar with a similarity score of 100.
Columns 'HUB 66' and 'Hub 66' are similar with a similarity score of 100.
Columns 'The Oberoi Gurgaon' and 'The Oberoi, Gurgaon' are similar with a similarity score of 97.
Columns 'RBSM Public school' and 'RHM Public School' are similar with a similarity score of 91.
Columns 'Health Care Pharmacy' and 'Health care pharmacy' are similar with a similarity score of 100.
Columns 'YES Bank ATM' and 'YES bank ATM' are similar with a similarity score of 100.
Columns 'The Millenium School' and 'The Millennium School' are similar with a similarity score of 98.
Columns 'International Tech Park Gurgaon,' and 'International Tech Park Gurgaon' are similar with a similarity score of 98.
Columns 'NH-8, IMT Manesar' and 'NH-8, Imt Manesar' are similar with a similarity score of 100.
Columns 'NH-8, IMT Manesar' and 'NH-8 IMT Manesar' are similar with a similarity score of 97.
Columns 'Euro International School, Sec 84' and 'Euro International School, Sector 84' are similar with a similarity score of 96.
Columns 'InfinityS Badminton Academy' and 'Infinitys Badminton Academy' are similar with a similarity score of 100.
Columns 'Kings International School' and 'Gems International School' are similar with a similarity score of 90.
Columns 'Rapid Metro Sector 55-56' and 'Rapid Metro Sector 56' are similar with a similarity score of 93.
Columns 'Yes Bank' and 'YES Bank' are similar with a similarity score of 100.
Columns 'Canara Bank' and 'CANARA BANK' are similar with a similarity score of 100.
Columns 'Paras Hospital' and 'Paras Hospitals' are similar with a similarity score of 97.
Columns 'Ektaa Hospitals' and 'Ektaa Hospital' are similar with a similarity score of 97.
Columns 'Gurugram Road' and 'Gurugram Rd' are similar with a similarity score of 92.
Columns 'The Signature Super Speciality Hospital' and 'Signature Super Speciality Hospital' are similar with a similarity score of 95.
Columns 'Country Inn & Suites by Radisson' and 'Country Inn and Suites by Radisson' are similar with a similarity score of 94.
Columns 'Country Inn & Suites by Radisson' and 'Country Inn & Suites By Radisson' are similar with a similarity score of 100.
Columns 'Sanjivani Hospital' and 'Sanjeevani Hospital' are similar with a similarity score of 92.
Columns 'Heritage badminton academy' and 'Heritage Badminton Academy' are similar with a similarity score of 100.
Columns 'ESIC Hospital' and 'ESIC HOSPITAL' are similar with a similarity score of 100.
Columns 'Omaxe City Centre Mall' and 'Omex City Centre Mall' are similar with a similarity score of 93.
Columns 'Matrikiran High School' and 'MatriKiran High School' are similar with a similarity score of 100.
Columns 'Shiv Mandir' and 'shiv Mandir' are similar with a similarity score of 100.

In [85]:
df_cleaned.head()

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,Shri Hanuman Ji Mandir,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Crown,550.0,54000.0,54000.0,54000.0,54000.0,6700.0,3800.0,54000.0,54000.0,7500.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Adani Brahma Samsara Vilasa,5300.0,54000.0,54000.0,54000.0,2500.0,8800.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Sobha City,1500.0,54000.0,54000.0,54000.0,6500.0,6700.0,5100.0,54000.0,54000.0,8200.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Signature Global City 93,54000.0,54000.0,54000.0,5500.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0

In [83]:
df_cleaned.fillna(54000,inplace=True)

In [84]:
df_cleaned.index = df.PropertyName

In [86]:
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(df_cleaned), columns=df_cleaned.columns, index=df_cleaned.index)

In [87]:
location_df_normalized

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,Shri Hanuman Ji Mandir,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-7.960979,-15.652476,-15.652476,-3.149592,-2.966108,-3.147217,-3.726615,-10.231739,-15.652476,-6.023233,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
M3M Crown,-7.998993,0.063888,0.063888,0.328277,0.368941,-3.054053,-3.529275,0.090308,0.063888,-6.009941,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
Adani Brahma Samsara Vilasa,-7.276720,0.063888,0.063888,0.328277,-3.129124,-2.903557,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
Sobha City,-7.854539,0.063888,0.063888,0.328277,-2.857430,-3.054053,-3.430606,0.090308,0.063888,-5.916893,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
Signature Global City 93,0.128476,0.063888,0.063888,-2.985606,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
Pyramid Urban Homes 2,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
Satya The Hermitage,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
BPTP Spacio,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888
SS The Coralwood,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888

In [88]:
cosine_sim3 = cosine_similarity(location_df_normalized)

In [90]:
def recommend_properties_with_scores(property_name, cosine_sim=cosine_sim3):
    # Get the index of the property that matches the name
    idx = location_df_normalized.index.get_loc(property_name)

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName':location_df_normalized.index[property_indices].tolist(),
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [91]:
recommend_properties_with_scores('Ireo Victory Valley')

                          PropertyName             SimilarityScore
0              Lion Infra Green Valley  (208, 0.27354578951194525)
1     Emaar MGF Emerald Floors Premier   (83, 0.20342633257165268)
2  International City by SOBHA Phase 2    (70, 0.1741531138813061)
3          Bestech Park View Grand Spa   (120, 0.1593417390662912)
4                 Shree Vardhman Flora   (123, 0.1298487009796303)

## combine 3 recommender to 1

In [92]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 30*cosine_sim1 + 20*cosine_sim2 + 8*cosine_sim3
    # cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('Ireo Victory Valley')

               PropertyName  SimilarityScore
0    Pioneer Urban Presidia        28.012345
1        Ambience Creacions        27.820875
2             DLF The Crest        24.201168
3             Pioneer Araya        23.423073
4               SS The Leaf        21.006901
..                      ...              ...
240          JMS The Nation       -14.744362
241     Shree Vardhman City       -15.001316
242          JMS Prime Land       -15.092978
243       Vatika Aspiration       -15.112630
244           Corona Greens       -15.786877

[245 rows x 2 columns]

In [93]:
import pickle
pickle.dump(cosine_sim1,open("cosine_sim1.pkl","wb"))

In [94]:
pickle.dump(cosine_sim2,open("cosine_sim2.pkl","wb"))
pickle.dump(cosine_sim3,open("cosine_sim3.pkl","wb"))

In [95]:

pickle.dump(df_cleaned,open("location_distance.pkl","wb"))